<?php

/**
 * @file
 * Contains block_grid_field.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_help().
 */
function block_grid_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the block_grid_field module.
    case 'help.page.block_grid_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Special Dropdown to indicate color of a stripe. See the settings page to enter some values') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function block_grid_field_theme() {
  return [
    'block_grid_select' => array(
      'render element' => 'element',
      'template' => 'block-grid-field-select',
      'base hook' => 'select',
    ),
  ];
}
