<?php

/**
 * @file
 * Contains block_grid_field.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Render\Element\RenderElement;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_help().
 */
function block_grid_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the block_grid_field module.
    case 'help.page.block_grid_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Special Dropdown to indicate color of a stripe. See the settings page to enter some values') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function block_grid_field_theme() {
  return [
    'block_grid_select' => array(
      'render element' => 'element',
      'template' => 'block-grid-field-select',
      'base hook' => 'select',
    ),
    'block_grid_fieldset' => array(
      'render element' => 'element',
      'template' => 'block-grid-field-fieldset',
      'base hook' => 'fieldset',
    ),
  ];
}

/**
 * Prepares variables for select element templates.
 *
 * Default template: select.html.twig.
 *
 * It is possible to group options together; to do this, change the format of
 * $options to an associative array in which the keys are group labels, and the
 * values are associative arrays in the normal $options format.
 *
 * @param $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 *     Properties used: #title, #value, #options, #description, #extra,
 *     #multiple, #required, #name, #attributes, #size.
 */
function block_grid_field_preprocess_block_grid_select(&$variables) {
  $element = $variables['element'];

  Element::setAttributes($element, array('id', 'name', 'size'));
  RenderElement::setAttributes($element, array('form-select'));

//  kint($element);
  $variables['attributes'] = $element['#attributes'];
  $variables['options'] = form_select_options($element);
}

/**
 * Prepares variables for fieldset element templates.
 *
 * Default template: fieldset.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 *     Properties used: #attributes, #children, #description, #id, #title,
 *     #value.
 */
//function template_preprocess_block_grid_fieldset(&$variables) {
//  $element = $variables['element'];
//  Element::setAttributes($element, array('id'));
//  RenderElement::setAttributes($element);
//  $variables['attributes'] = isset($element['#attributes']) ? $element['#attributes'] : array();
//  $variables['prefix'] = isset($element['#field_prefix']) ? $element['#field_prefix'] : NULL;
//  $variables['suffix'] = isset($element['#field_suffix']) ? $element['#field_suffix'] : NULL;
//  $variables['title_display'] = isset($element['#title_display']) ? $element['#title_display'] : NULL;
//  $variables['children'] = $element['#children'];
//  $variables['required'] = !empty($element['#required']) ? $element['#required'] : NULL;
//
//  if (isset($element['#title']) && $element['#title'] !== '') {
//    $variables['legend']['title'] = ['#markup' => $element['#title']];
//  }
//
//  $variables['legend']['attributes'] = new Attribute();
//  // Add 'visually-hidden' class to legend span.
//  if ($variables['title_display'] == 'invisible') {
//    $variables['legend_span']['attributes'] = new Attribute(array('class' => 'visually-hidden'));
//  }
//  else {
//    $variables['legend_span']['attributes'] = new Attribute();
//  }
//
//  if (!empty($element['#description'])) {
//    $description_id = $element['#attributes']['id'] . '--description';
//    $description_attributes['id'] = $description_id;
//    $variables['description']['attributes'] = new Attribute($description_attributes);
//    $variables['description']['content'] = $element['#description'];
//
//    // Add the description's id to the fieldset aria attributes.
//    $variables['attributes']['aria-describedby'] = $description_id;
//  }
//
//  // Suppress error messages.
//  $variables['errors'] = NULL;
//}
